resources:
- name: capi-workspace
  type: git
  source:
    branch: new-workstations
    uri: https://github.com/cloudfoundry/capi-workspace

jobs:
  - name: create-and-setup-workspace
    plan:
    - get: capi-workspace
    - task: do-stuff
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: google/cloud-sdk
        params:
          GCP_SERVICE_ACCOUNT_KEY: ((arya_gcp_json_key))
        inputs:
        - name: capi-workspace
        run:
          path: bash
          args:
            - -c
            - |
              set -e
              gcloud auth activate-service-account --key-file=<(echo $GCP_SERVICE_ACCOUNT_KEY)
              echo "Creating some michael VM"
              gcloud compute instances create capi-ws-michael --zone "us-central1-a" --project "cf-capi-arya" --boot-disk-size=50GB --machine-type=e2-standard-8 --tags=workstations --image-family=ubuntu-2204-lts --image-project=ubuntu-os-cloud
              echo "wait 30 for instance to be up"
              sleep 30
              echo "copy capi-workspace over"
              gcloud compute ssh --zone "us-central1-a" "pivotal@capi-ws-michael" --project "cf-capi-arya" -q --command 'mkdir -p ~/workspace'
              gcloud compute scp --recurse capi-workspace/ --zone "us-central1-a" "pivotal@capi-ws-michael:~/workspace" --project "cf-capi-arya" -q
              echo "run set-up-new-machine.sh on workstation"
              gcloud compute ssh --zone "us-central1-a" "pivotal@capi-ws-michael" --project "cf-capi-arya" -q --command '~/workspace/capi-workspace/set-up-new-machine.sh'
              echo "you should probably check to see if this worked now, it probably did!"

  - name: delete-workspace
    plan:
    - task: be-gone
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: google/cloud-sdk
        params:
          GCP_SERVICE_ACCOUNT_KEY: ((arya_gcp_json_key))
        run:
          path: bash
          args:
            - -c
            - |
              set -e
              gcloud auth activate-service-account --key-file=<(echo $GCP_SERVICE_ACCOUNT_KEY)
              echo "deleting some michael VM"
              gcloud compute instances delete capi-ws-michael --zone "us-central1-a" --project "cf-capi-arya" -q